### ISSUE TITLE
How you guys make coated glasses?

### ISSUE THREAD

**Issue by supertask** [1-10/ProjectNorthStar_1-10_custom#1]
It is the most important part which you guys have done, I think.
Please tell us.

**Comment by hirano1-10** [comment]
Hi. We requested a vendor for vacuum deposition.
If you look search, you will find a BtoC vendor.

**Comment by supertask** [comment]
Thank you. I appreciate with your comment and advice. It must be expensive I think.
I wonder how much it is. Is it more expensive than 100 us dollars? of course If you can tell.

**Comment by hirano1-10** [comment]
In small quantities it will be expensive.
It possibly be cheaper if you collect members and vacuum deposition them.
